import { z } from 'zod';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import {
  rpcCall,
  auditLog,
  isReadOnly,
  assertWriteEnabled,
  VerusError,
  checkSpendingLimits,
} from '@verusidx/shared';

// ---------------------------------------------------------------------------
// Response helpers
// ---------------------------------------------------------------------------

function ok(data: unknown) {
  return {
    content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }],
  };
}

function fail(category: string, message: string) {
  return {
    content: [{ type: 'text' as const, text: JSON.stringify({ error: category, message }, null, 2) }],
    isError: true as const,
  };
}

function handleError(err: unknown) {
  if (err instanceof VerusError) {
    return fail(err.category, err.message);
  }
  return fail('INTERNAL_ERROR', err instanceof Error ? err.message : 'Unknown error');
}

const SERVER_NAME = 'verusidx-marketplace-mcp';

// ---------------------------------------------------------------------------
// Tool registration
// ---------------------------------------------------------------------------

export function registerTools(server: McpServer): void {
  // ------ Read-only tools (always registered) ------

  server.tool(
    'getoffers',
    'Get all open offers for a specific currency or identity. Returns both buy and sell offers — offers of the asset and offers for the asset. Use iscurrency to switch between currency offers and identity offers. Response keys are dynamic and generated by the daemon based on the queried asset — parse them dynamically. Use this to discover what\'s available on the market before making or taking offers.',
    {
      chain: z.string().describe('Chain to query (e.g., "VRSC", "vrsctest")'),
      currencyorid: z.string().describe('Currency name/i-address or identity name/i-address to check for offers'),
      iscurrency: z.boolean().optional().describe('If true, look for currency offers. If false (default), look for identity offers.'),
      withtx: z.boolean().optional().describe('If true, include serialized hex of the exchange transaction for signing. Default: false.'),
    },
    async ({ chain, currencyorid, iscurrency, withtx }) => {
      try {
        // getoffers "currencyorid" (iscurrency) (withtx)
        const params: unknown[] = [currencyorid];
        if (iscurrency !== undefined || withtx !== undefined) {
          params.push(iscurrency ?? false);
        }
        if (withtx !== undefined) {
          params.push(withtx);
        }
        const result = await rpcCall(chain, 'getoffers', params);
        return ok(result);
      } catch (err) {
        return handleError(err);
      }
    },
  );

  server.tool(
    'listopenoffers',
    'List open offers from the current wallet. Shows what this wallet has offered on-chain. Can filter by expired/unexpired status. Use this to check the status of offers the agent has created, or to find offers that need to be closed.',
    {
      chain: z.string().describe('Chain to query (e.g., "VRSC", "vrsctest")'),
      unexpired: z.boolean().optional().describe('Include unexpired (active) offers. Default: true.'),
      expired: z.boolean().optional().describe('Include expired offers. Default: true.'),
    },
    async ({ chain, unexpired, expired }) => {
      try {
        // listopenoffers (unexpired) (expired)
        const params: unknown[] = [];
        if (unexpired !== undefined || expired !== undefined) {
          params.push(unexpired ?? true);
        }
        if (expired !== undefined) {
          params.push(expired);
        }
        const result = await rpcCall(chain, 'listopenoffers', params);
        return ok(result);
      } catch (err) {
        return handleError(err);
      }
    },
  );

  // ------ Write tools (registered only when not read-only) ------

  if (!isReadOnly()) {
    server.tool(
      'makeoffer',
      'Create a new on-chain atomic swap offer. Offers are fully decentralized — no intermediary, no escrow. The offer transaction locks the offered asset on-chain until the offer is taken, expires, or is closed. Supports currency-for-currency, currency-for-identity, identity-for-currency, and identity-for-identity swaps. For currency offers, use {"currency": "name", "amount": n}. For identity offers (without control tokens), use {"identity": "name@"} or a full identity definition. If an identity has a control token (flags: 5), offer/request the control token as a currency instead: {"currency": "idname.parent", "amount": 0.00000001}. Always include parent in identity definitions.',
      {
        chain: z.string().describe('Chain to transact on (e.g., "VRSC", "vrsctest")'),
        fromaddress: z.string().describe('Source address for funds. If the user has not specified a preferred address, ask which address to use or if they prefer a wildcard ("*", "R*", "i*", or "z*" for private txs).'),
        offer: z.record(z.unknown()).describe('What to offer — {"currency": "name", "amount": n} for currency, or {"identity": "name@"} / full identity definition for identity.'),
        changeaddress: z.string().describe('Transparent address or VerusID ("ID@") for change.'),
        expiryheight: z.number().optional().describe('Block height at which this offer expires. Default: current height + 20 (~20 minutes). Set higher for marketplace listings.'),
        for: z.record(z.unknown()).describe('What to accept in return — {"currency": "name", "amount": n, "address": "dest"} for currency (address is REQUIRED — can be R-address, VerusID name@, or i-address), or full identity definition (with parent) for identity.'),
        returntx: z.boolean().optional().describe('If true, return signed transaction hex instead of broadcasting. Default: false.'),
        feeamount: z.number().optional().describe('Custom fee amount. Default: 0.0001.'),
      },
      async ({ chain, fromaddress, offer, changeaddress, expiryheight, for: forObj, returntx, feeamount }) => {
        try {
          assertWriteEnabled();

          // Spending limits check for currency offers
          const offerRecord = offer as Record<string, unknown>;
          if (offerRecord.currency && typeof offerRecord.amount === 'number') {
            const amounts = new Map<string, number>();
            amounts.set(offerRecord.currency as string, offerRecord.amount as number);
            checkSpendingLimits(amounts);
          }

          // makeoffer fromaddress '{"changeaddress":"...","expiryheight":n,"offer":{...},"for":{...}}' (returntx) (feeamount)
          const offerObj: Record<string, unknown> = {
            changeaddress,
            offer,
            for: forObj,
          };
          if (expiryheight !== undefined) {
            offerObj.expiryheight = expiryheight;
          }

          const params: unknown[] = [fromaddress, offerObj];
          if (returntx !== undefined || feeamount !== undefined) {
            params.push(returntx ?? false);
          }
          if (feeamount !== undefined) {
            params.push(feeamount);
          }

          const result = await rpcCall(chain, 'makeoffer', params);

          auditLog({
            server: SERVER_NAME,
            tool: 'makeoffer',
            chain,
            params: { fromaddress, offer, for: forObj, expiryheight, returntx },
            result,
            success: true,
          });

          return ok(result);
        } catch (err) {
          return handleError(err);
        }
      },
    );

    server.tool(
      'takeoffer',
      'Accept an existing on-chain offer. Creates and posts a transaction that atomically executes the exchange — both sides swap in a single transaction, or neither does. The offer transaction must have at least 1 confirmation before it can be taken. Before taking, verify the offer hasn\'t expired by checking blockexpiry against current block height. deliver is what you give, accept is what you get. For currency: deliver {"currency": "name", "amount": n}, accept {"address": "addr", "currency": "name", "amount": n}. For identity: deliver "name@" (string), accept is full identity definition with parent. If the identity has a control token, use control token currency instead.',
      {
        chain: z.string().describe('Chain to transact on (e.g., "VRSC", "vrsctest")'),
        fromaddress: z.string().describe('Source address for funds. If the user has not specified a preferred address, ask which address to use or if they prefer a wildcard ("*", "R*", "i*", or "z*" for private txs).'),
        txid: z.string().optional().describe('Transaction ID of the offer to accept (from getoffers or makeoffer). Either txid or tx is required.'),
        tx: z.string().optional().describe('Hex transaction to complete (from makeoffer with returntx=true). Either txid or tx is required.'),
        changeaddress: z.string().describe('Transparent address or VerusID for change.'),
        deliver: z.union([z.string(), z.record(z.unknown())]).describe('What the taker delivers — "name@" (identity) or {"currency": "name", "amount": n} (currency).'),
        accept: z.record(z.unknown()).describe('What the taker receives — {"address": "addr", "currency": "name", "amount": n} (currency) or full identity definition (identity).'),
        returntx: z.boolean().optional().describe('If true, return signed transaction hex instead of broadcasting. Default: false.'),
        feeamount: z.number().optional().describe('Custom fee amount. Default: 0.0001.'),
      },
      async ({ chain, fromaddress, txid, tx, changeaddress, deliver, accept, returntx, feeamount }) => {
        try {
          assertWriteEnabled();

          if (!txid && !tx) {
            return fail('INVALID_PARAMS', 'Either txid or tx must be provided.');
          }

          // Spending limits check for currency delivery
          if (typeof deliver === 'object' && deliver !== null) {
            const deliverRecord = deliver as Record<string, unknown>;
            if (deliverRecord.currency && typeof deliverRecord.amount === 'number') {
              const amounts = new Map<string, number>();
              amounts.set(deliverRecord.currency as string, deliverRecord.amount as number);
              checkSpendingLimits(amounts);
            }
          }

          // takeoffer fromaddress '{"txid":"...","changeaddress":"...","deliver":{...},"accept":{...}}' (returntx) (feeamount)
          const takeObj: Record<string, unknown> = {
            deliver,
            accept,
          };
          if (txid !== undefined) takeObj.txid = txid;
          if (tx !== undefined) takeObj.tx = tx;
          takeObj.changeaddress = changeaddress;

          const params: unknown[] = [fromaddress, takeObj];
          if (returntx !== undefined || feeamount !== undefined) {
            params.push(returntx ?? false);
          }
          if (feeamount !== undefined) {
            params.push(feeamount);
          }

          const result = await rpcCall(chain, 'takeoffer', params);

          auditLog({
            server: SERVER_NAME,
            tool: 'takeoffer',
            chain,
            params: { fromaddress, txid: txid || '(hex)', deliver, accept: { ...accept as Record<string, unknown>, address: '...' }, returntx },
            result,
            success: true,
          });

          return ok(result);
        } catch (err) {
          return handleError(err);
        }
      },
    );

    server.tool(
      'closeoffers',
      'Close (cancel) open offers and reclaim the locked funds. Returns null on success. Always closes expired offers automatically, even if no parameters are given. When specific offer txids are provided, closes only those offers. Use this to cancel offers that are no longer wanted, or as periodic cleanup to reclaim funds from expired offers.',
      {
        chain: z.string().describe('Chain to transact on (e.g., "VRSC", "vrsctest")'),
        txids: z.array(z.string()).optional().describe('Array of offer transaction IDs to close. If omitted, closes all expired offers.'),
        destination: z.string().optional().describe('Transparent or private address to send reclaimed funds to.'),
        privatefundsdestination: z.string().optional().describe('Private (Sapling) address for native funds only.'),
      },
      async ({ chain, txids, destination, privatefundsdestination }) => {
        try {
          assertWriteEnabled();

          // closeoffers '["txid1","txid2"]' ("destination") ("privatefundsdestination")
          const params: unknown[] = [txids ?? []];
          if (destination !== undefined || privatefundsdestination !== undefined) {
            params.push(destination ?? '');
          }
          if (privatefundsdestination !== undefined) {
            params.push(privatefundsdestination);
          }

          const result = await rpcCall(chain, 'closeoffers', params);

          auditLog({
            server: SERVER_NAME,
            tool: 'closeoffers',
            chain,
            params: { txids, destination },
            result,
            success: true,
          });

          return ok(result);
        } catch (err) {
          return handleError(err);
        }
      },
    );
  }
}
